#!/usr/bin/env python3
# Diceware generator in Python 3

import os,argparse
from os.path import *

def getwords(wordlist):
   lists={
      'diceware': 'diceware.txt',
      'beale': 'beale.txt'
      }
   path=os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
   with open(os.path.join(path,lists[wordlist]),'r') as f:
      return f.readlines()

def getidx():
   def __inner():
      b=list(os.urandom(2))
      return (b[1]<<8)+b[0]
   x=__inner()
   while x > 7775:
      x=__inner()
   return x

def pick(n, wordlist):
   pw=[]
   for i in range(n):
      idx=getidx()
      word=wordlist[idx].strip().split(' ')
      pw.append(word[1])
   return pw

if __name__=='__main__':
   parser=argparse.ArgumentParser(description='Diceware generator in Python 3')
   parser.add_argument('-v','--version',action='version',version='diceware 1.0')
   parser.add_argument('-l','--list',choices=['diceware','beale'],
                       default='beale',help='wordlist to use')
   parser.add_argument('words',nargs='?',default=8,type=int,
                       help='number of words to generate')
   options=parser.parse_args()
   ls=pick(options.words, getwords(options.list))
   print(' '.join(ls))
